# Generated by Django 5.1.4 on 2025-01-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.BigIntegerField(),
        ),
    ]
