# Generated by Django 5.1.4 on 2025-01-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0002_alter_user_tg_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logins_model',
            options={'ordering': ['id']},
        ),
    ]
