# Generated by Django 5.1.4 on 2025-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0003_alter_logins_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
